### ISSUE TITLE
The meaning of TAw & TAg

### ISSUE THREAD

**Issue by Lllydialee** [mmasana/FACIL#15]
Thank you very much for providing such an amazing continual learning framework!

I am a little confused about the evaluation metric: TAw acc & TAg acc, could you please explain their meaning respectively? Thank you very much in advance!!

![1](https://user-images.githubusercontent.com/74192106/153479365-70bd00f9-f51a-4548-993c-6561000eb2cc.png)

**Comment by mmasana** [comment]
Hi @Lllydialee,
TAw means _task aware_, and TAg means _task agnostic_. The first one uses the task-ID during evaluation, meaning that you only have to predict from the classes within the task. This is the case for task-incremental learning. For the second case, you do not have access to the task-ID, therefore you predict from all classes learned so far, which is the case for class-incremental learning. In the output that you show, each column represents each of the learned tasks, and each row represents at which task were those metrics calculated. That's why the top diagonal is empty, because you cannot evaluate on task 5 when you are at task 3 (task 5 has not happened yet at that point). The last column is an average over all accuracies of all tasks seen so far.

**Comment by Lllydialee** [comment]
Really thank you for explanation! Thanks!
