### ISSUE TITLE
Some question about the approach 'BiC'

### ISSUE THREAD

**Issue by ZhenbangDu** [mmasana/FACIL#16]
Hello! Thank you for your amazing work! But it seems that in BiC, in line 102, when creating the dataset val_old, the code doesn't consider the situation that "self.exemplars_dataset.max_num_exemplars_per_class != 0".

**Comment by mmasana** [comment]
Hi @YixianDu,
happy to hear you like our framework!

> But it seems that in BiC, in line 102, when creating the dataset val_old, the code doesn't consider the situation that "self.exemplars_dataset.max_num_exemplars_per_class != 0".

That is correct. In the condition of line 102 we remove extra exemplars from previous classes. But this is only done when the type of memory is fixed (and therefore has a limit). In the case of a growing memory, we do not want to remove any exemplar, and that's why we do not check if `self.exemplars_dataset.max_num_exemplars_per_class != 0`.

Hope that solves the confusion :)
