### ISSUE TITLE
TaskID

### ISSUE THREAD

**Issue by AndreGuerra123** [mmasana/FACIL#24]
Hi, this is not really an issue.
I'm currently developing a classification model which is trained by event-driven samples. The number of labels/classes grows as new events are produced and consumed by the model. I partially read :) your article but couldn't not find a reference to what is a task ID. (Is this a batch number for the training set?) Overall I would like to congratulate you for this work since it seems to extensively deal with a real issue.

**Comment by mmasana** [comment]
Hi Andre,
due to being in an incremental learning setting, where we expect data to come in tasks over time, the task-ID is the label of the task for the evaluated image. Each task is composed of one or more classes, therefore having access to the task label, reduces the number of classes from which the model has to predict to those only available at task N (see Fig.1). In the case of the class-incremental survey, the premise is that you do not have access to the task-ID during test time (after training), therefore you have to predict the class from all the classes learned so far.
