### ISSUE TITLE
Imagenet100

### ISSUE THREAD

**Issue by zijGao** [mmasana/FACIL#26]
Dear author,

Thanks for your great work. It really helps me a lot!

I wonder if you tried to use imagenet_100 (imagenet_subset) as the dataset? I tried to use the imagenet_subset dataset but failed. It really helps me if you can provide the code about using the imagenet_subset dataset!

**Comment by mmasana** [comment]
Hi,

happy to hear that you like our work!

We have used the `imagenet_subset` dataset without problem. However, you need to have the ImageNet dataset set up for yourself, since I think it is not available as a `torchvision` import. To add the dataset, you can follow the instructions [here](https://github.com/mmasana/FACIL/tree/master/src/datasets#adding-new-datasets). Or if you have tried that, then I would need more information on which error you get.

**Comment by wangsen1312** [comment]
@mmasana Thank you for your information. Could you share where we can download the imagenet100 dataset or we can generate one from original imagenet?

**Comment by mmasana** [comment]
You can download the dataset from their [website](https://www.image-net.org/download.php), and then create the the dataset `.txt` files as explained in the [link](https://github.com/mmasana/FACIL/tree/master/src/datasets#adding-new-datasets) from last comment.

In the case of the Imagenet subset of 100 classes, you can either create the `train.txt` and `test.txt` only containing the images from the corresponding first 100 classes, or you can use the `.txt` files with all classes and then use the `'class_order'` option to use only those classes that correspond to the split you want.

**Comment by wangsen1312** [comment]
@mmasana Thank you for your reply, it's working now!
