### ISSUE TITLE
Adding a new dataset

### ISSUE THREAD

**Issue by andreadaou** [mmasana/FACIL#29]
Hi !

As mentioned in [README.md](https://github.com/mmasana/FACIL/blob/master/src/datasets/README.md) to add a custom dataset: 
- Create a new entry in [dataset_config.py](https://colab.research.google.com/drive/dataset_config.py), add the folder with the data in path and any other transformations or class ordering needed.
- The option from line 135 in [data_loader.py](https://github.com/mmasana/FACIL/blob/master/src/datasets/data_loader.py) should be enough. 
- In the same folder as the data add a train.txt and a test.txt files.

If I follow the steps mentioned above to add **newdataset**, I will get:
![FACIL](https://user-images.githubusercontent.com/72491086/213171100-5b553526-4a95-49ab-a55f-0e814ba50502.PNG)
![dataset_config_newdataset](https://user-images.githubusercontent.com/72491086/213171103-31094d6f-63b7-4afc-9a14-4c5f457563b0.PNG)
![data_loader_newdataset](https://user-images.githubusercontent.com/72491086/213171104-9a5b6609-6f0a-4c24-96b3-bdd7301e1c48.PNG)

Till now, is this correct?

In the **newdataset** folder added in **data** folder shown in **FACIL capture**, should I insert all the train and test images as .jpg files? In addition to train.txt and test.txt ?

Sorry for this long question but I'm having a problem when adding a custom dataset. Appreciate your help !! Thank you :)

**Comment by mmasana** [comment]
If you are using our system of `train.txt` and `test.txt` files. Then you do not need lines 136 and 137 (from the third image you posted). It should work directly with the part from 139-145. With the else-branch you have created the dataset is probably empty, and that's why it would not be working.

The `.txt.` files will contain as the first column the path to the images, so it doesn't matter where the images are stored as long as the paths are correct. I would recommend using absolute paths.

The `dataset_config` looks correct.

Usually, the `data` folder is created inside the FACIL folder, same "height" in the tree as `src` or `scripts`. So that could be an issue too?

Feel free to post the errors you get so I know where they might be coming from.

**Comment by andreadaou** [comment]
Thank you so much @mmasana !! I believe the code is now operating correctly.

I will post the new errors if any occur (hopefully none will). Thank you again !
